### ISSUE TITLE
context.Context support is missing

### ISSUE THREAD

**Issue by brenol** [twilio/twilio-go#98]
### Issue Summary
Not really a bug, but a missing functionality. Expected to see methods with `context.Context` support. However, currently there is no support for it and this makes it not being possible to do proper cancellation with twilio's API.

### Code Snippet
N/A

### Exception/Log
N/A

### Technical details:
* twilio-go version: v0.12.0
* go version: 1.16.5

**Comment by thinkingserious** [comment]
Hello @brenol,

Thank you for taking the time to report this feature request! This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by kevinburke** [comment]
You might want to also add a note in the README that the API is going to change, unless you are going to double up every single endpoint like AWS does (CreateMessage and CreateMessageWithContext, etc.)

**Comment by natebrennand** [comment]
Hi @thinkingserious , I'd be willing to take this on if you can direct me on how you want the API's evolved.
[I really appreciate the ability to provide your own HTTP client](https://pkg.go.dev/github.com/twilio/twilio-go@v0.24.0/client#Client), but not having accessing the `context.Context` is limiting our ability to instrument the client.

I envision that both the client's and API packages are going to need meaningful changes to accommodate this:

Approach 1 - break API's:
- Update `client.RequestHandler` & `client.BaseClient` to take in `context.Context` as the first argument.
- Then update all API's to also take in `context.Context` as the first argument.

Approach 2 - deprecate and expose API's w/ context.
- Add `client.RequestHandlerWithCtx` and `client.BaseClientWithCtx`
- Add API's to also take in `context.Context` as the first argument. otherwise same API's with `WithCtx` appended to the function names
- Update internals so that the `DoFoo` API's all call `DoFooWithCtx(context.Background(), ....)`
- internal methods to wrap `client.RequestHandler`/`client.BaseClient` into their context-using versions

I'm generally assuming y'all would prefer adding methods rather than breaking.
Please let me know how you'd like these changes to look.

**Comment by rakatyal** [comment]
Hi @natebrennand, thank you for your suggestions! We like the approach 2, if you could submit a PR with a proof of concept, we will work on getting the changes inside the generator.

**Comment by natebrennand** [comment]
> Hi @natebrennand, thank you for your suggestions! We like the approach 2, if you could submit a PR with a proof of concept, we will work on getting the changes inside the generator.

I've got PR's open to update the underlying client and the SDK to support this:
- https://github.com/twilio/twilio-go/pull/197
- https://github.com/twilio/twilio-oai-generator/pull/301

**Comment by dillonstreator** [comment]
Re-opening seeing that #196 and #197 were both reverted
https://github.com/twilio/twilio-go/commit/79f196ed9040e4d8ced77170a19f8fbb621fae2c
https://github.com/twilio/twilio-go/commit/e89399c03e9e5ef236058bdb394d0bed427d9ae5

@childish-sambino any update on the status of introducing context support?

**Comment by dillonstreator** [comment]
@childish-sambino can we re-open this seeing that #196 and #197 were both reverted?
https://github.com/twilio/twilio-go/commit/79f196ed9040e4d8ced77170a19f8fbb621fae2c
https://github.com/twilio/twilio-go/commit/e89399c03e9e5ef236058bdb394d0bed427d9ae5

Curious why the work was reverted? Any plans to introduce context support?

**Comment by kbolino** [comment]
Am I missing something? This is marked as done but version 1.7.1 of the API, released 5 days ago, does not seem to have support for context.

For example, the signature of [CreateVerification](https://pkg.go.dev/github.com/twilio/twilio-go@v1.7.1/rest/verify/v2#ApiService.CreateVerification) looks like this:

```go
func (c *ApiService) CreateVerification(ServiceSid string, params *CreateVerificationParams) (*VerifyV2Verification, error)
```

whereas I'm expecting it to look like this:

```go
func (c *ApiService) CreateVerification(ctx context.Context, ServiceSid string, params *CreateVerificationParams) (*VerifyV2Verification, error)
```

**Comment by Makpoc** [comment]
Hello. I'd like to repeat the last question from kbolino. Support for context was added and then reverted with e89399c and 79f196e . Was this intentional change or was it a bad merge/regenerate?

**Comment by Kcrong** [comment]
Hi. I'd like to inquire about any updates regarding this issue.
cc @childish-sambino

**Comment by Kcrong** [comment]
Hi. I'd like to inquire about any updates regarding this issue.

**Comment by mwajeeh** [comment]
Any update here?
